name: birdclef
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - librosa>=0.10
  - scikit-learn
  - pandas
  - matplotlib
  - seaborn
  - tqdm
  - ipykernel
  - jupyter
  - pip
  - pip:
    # Same stack as pip install torch torchvision torchaudio
    # --index-url https://download.pytorch.org/whl/cu124
    - --extra-index-url https://download.pytorch.org/whl/cu124
    - torch==2.6.0+cu124
    - torchvision==0.21.0+cu124
    - torchaudio==2.6.0+cu124
    - timm
    - einops
    - soundfile
    - kaggle
